Reformat validation

diff --git a/.github/actions/install-dependencies/action.yml b/.github/actions/install-dependencies/action.yml
--- a/.github/actions/install-dependencies/action.yml
+++ b/.github/actions/install-dependencies/action.yml
@@ -17,7 +17,10 @@ runs:
     - name: Validate Inputs
       shell: bash
       run: |
-        [ -z "${{ inputs.python-version }}" ] && echo "Missing input: python-version" && exit 1
+        if [ -z "${{ inputs.python-version }}" ]; then
+          echo "Missing input: python-version"
+          exit 1
+        fi
 
     - name: Set up Python ${{ inputs.python-version }}
       uses: actions/setup-python@v5
